# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import response_synthesizer_pb2 as response__synthesizer__pb2


class ResponseSynthesizerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.summarizeResponse = channel.unary_stream(
                '/ResponseSynthesizer/summarizeResponse',
                request_serializer=response__synthesizer__pb2.getFinalAnswerRequest.SerializeToString,
                response_deserializer=response__synthesizer__pb2.getFinalAnswerResponse.FromString,
                )
        self.getSynthesizerDefaultParams = channel.unary_unary(
                '/ResponseSynthesizer/getSynthesizerDefaultParams',
                request_serializer=response__synthesizer__pb2.FinalEmpty.SerializeToString,
                response_deserializer=response__synthesizer__pb2.FinalParams.FromString,
                )


class ResponseSynthesizerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def summarizeResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSynthesizerDefaultParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResponseSynthesizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'summarizeResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.summarizeResponse,
                    request_deserializer=response__synthesizer__pb2.getFinalAnswerRequest.FromString,
                    response_serializer=response__synthesizer__pb2.getFinalAnswerResponse.SerializeToString,
            ),
            'getSynthesizerDefaultParams': grpc.unary_unary_rpc_method_handler(
                    servicer.getSynthesizerDefaultParams,
                    request_deserializer=response__synthesizer__pb2.FinalEmpty.FromString,
                    response_serializer=response__synthesizer__pb2.FinalParams.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ResponseSynthesizer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ResponseSynthesizer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def summarizeResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ResponseSynthesizer/summarizeResponse',
            response__synthesizer__pb2.getFinalAnswerRequest.SerializeToString,
            response__synthesizer__pb2.getFinalAnswerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getSynthesizerDefaultParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResponseSynthesizer/getSynthesizerDefaultParams',
            response__synthesizer__pb2.FinalEmpty.SerializeToString,
            response__synthesizer__pb2.FinalParams.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
