# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import index_builder_pb2 as index__builder__pb2


class IndexBuilderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.buildIndex = channel.unary_unary(
                '/IndexBuilder/buildIndex',
                request_serializer=index__builder__pb2.buildIndexRequest.SerializeToString,
                response_deserializer=index__builder__pb2.buildIndexResponse.FromString,
                )
        self.getIndex = channel.unary_unary(
                '/IndexBuilder/getIndex',
                request_serializer=index__builder__pb2.getBuildIndexRequest.SerializeToString,
                response_deserializer=index__builder__pb2.getBuildIndexResponse.FromString,
                )
        self.deleteIndex = channel.unary_unary(
                '/IndexBuilder/deleteIndex',
                request_serializer=index__builder__pb2.deleteBuildIndexRequest.SerializeToString,
                response_deserializer=index__builder__pb2.deleteBuildIndexResponse.FromString,
                )


class IndexBuilderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def buildIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndexBuilderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'buildIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.buildIndex,
                    request_deserializer=index__builder__pb2.buildIndexRequest.FromString,
                    response_serializer=index__builder__pb2.buildIndexResponse.SerializeToString,
            ),
            'getIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.getIndex,
                    request_deserializer=index__builder__pb2.getBuildIndexRequest.FromString,
                    response_serializer=index__builder__pb2.getBuildIndexResponse.SerializeToString,
            ),
            'deleteIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteIndex,
                    request_deserializer=index__builder__pb2.deleteBuildIndexRequest.FromString,
                    response_serializer=index__builder__pb2.deleteBuildIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IndexBuilder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IndexBuilder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def buildIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IndexBuilder/buildIndex',
            index__builder__pb2.buildIndexRequest.SerializeToString,
            index__builder__pb2.buildIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IndexBuilder/getIndex',
            index__builder__pb2.getBuildIndexRequest.SerializeToString,
            index__builder__pb2.getBuildIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IndexBuilder/deleteIndex',
            index__builder__pb2.deleteBuildIndexRequest.SerializeToString,
            index__builder__pb2.deleteBuildIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
