# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query_engine.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12query_engine.proto\"\x8d\x01\n\x19getAnswerCitationsRequest\x12\x16\n\x0e\x63onversationId\x18\x01 \x01(\t\x12\x13\n\x0bsubQuestion\x18\x02 \x01(\t\x12\x1a\n\x06params\x18\x03 \x01(\x0b\x32\n.SubParams\x12\x10\n\x08toolName\x18\x04 \x01(\t\x12\x15\n\rsubQuestionId\x18\x05 \x01(\t\"a\n\x1agetAnswerCitationsResponse\x12\x0e\n\x06\x41nswer\x18\x01 \x01(\t\x12#\n\tcitations\x18\x02 \x03(\x0b\x32\x10.SubConvCitation\x12\x0e\n\x06status\x18\x03 \x01(\t\"e\n\x0fSubConvCitation\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07pagenum\x18\x02 \x01(\x05\x12\x13\n\x0b\x64ocument_id\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x0c\n\x04node\x18\x05 \x01(\x0c\"\n\n\x08SubEmpty\"\xd1\x01\n\tSubParams\x12\x0c\n\x04qe_k\x18\x01 \x01(\x05\x12\x10\n\x08qe_top_k\x18\x02 \x01(\x05\x12\x16\n\x0eqe_temperature\x18\x03 \x01(\x02\x12\x19\n\x11qe_max_new_tokens\x18\x04 \x01(\x05\x12\x1a\n\x12qe_score_threshold\x18\x05 \x01(\x02\x12\x1d\n\x15qe_repetition_penalty\x18\x06 \x01(\x02\x12\x19\n\x11qe_reranker_top_n\x18\x07 \x01(\x05\x12\x1b\n\x13qe_similarity_top_k\x18\x08 \x01(\x05\" \n\x10SubLengthRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"#\n\x11SubLengthResponse\x12\x0e\n\x06length\x18\x01 \x01(\x05\"6\n\x1dSubModelContextLengthResponse\x12\x15\n\rcontextLength\x18\x01 \x01(\x05\x32\x99\x02\n\x0bQueryEngine\x12O\n\x12getAnswerCitations\x12\x1a.getAnswerCitationsRequest\x1a\x1b.getAnswerCitationsResponse\"\x00\x12\x42\n\x13getSubContextLength\x12\t.SubEmpty\x1a\x1e.SubModelContextLengthResponse\"\x00\x12.\n\x13getSubDefaultParams\x12\t.SubEmpty\x1a\n.SubParams\"\x00\x12\x45\n\x1agetSubBatchTokenizedLength\x12\x11.SubLengthRequest\x1a\x12.SubLengthResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_engine_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETANSWERCITATIONSREQUEST']._serialized_start=23
  _globals['_GETANSWERCITATIONSREQUEST']._serialized_end=164
  _globals['_GETANSWERCITATIONSRESPONSE']._serialized_start=166
  _globals['_GETANSWERCITATIONSRESPONSE']._serialized_end=263
  _globals['_SUBCONVCITATION']._serialized_start=265
  _globals['_SUBCONVCITATION']._serialized_end=366
  _globals['_SUBEMPTY']._serialized_start=368
  _globals['_SUBEMPTY']._serialized_end=378
  _globals['_SUBPARAMS']._serialized_start=381
  _globals['_SUBPARAMS']._serialized_end=590
  _globals['_SUBLENGTHREQUEST']._serialized_start=592
  _globals['_SUBLENGTHREQUEST']._serialized_end=624
  _globals['_SUBLENGTHRESPONSE']._serialized_start=626
  _globals['_SUBLENGTHRESPONSE']._serialized_end=661
  _globals['_SUBMODELCONTEXTLENGTHRESPONSE']._serialized_start=663
  _globals['_SUBMODELCONTEXTLENGTHRESPONSE']._serialized_end=717
  _globals['_QUERYENGINE']._serialized_start=720
  _globals['_QUERYENGINE']._serialized_end=1001
# @@protoc_insertion_point(module_scope)
