
name: Deploy to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build backend, tag, and push image to Amazon ECR
        id: build-image-backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ragger-backend
          IMAGE_TAG: Lasted
        run: |
          echo "image-backend=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "image-url=$ECR_REGISTRY/$ECR_REPOSITORY" >> $GITHUB_OUTPUT
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG Dockerfile.backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build synthesizer, tag, and push image to Amazon ECR
        id: build-image-synthesizer
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ragger-synthesizer
            IMAGE_TAG: Lasted
        run: |
            echo "image-syn=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG Dockerfile.synthesizer
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
      - name: install terraform
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://releases.hashicorp.com/terraform/1.8.1/terraform_1.8.1_linux_amd64.zip
          unzip terraform_1.8.1_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          echo terraform --version
          cd infra
          terraform init -backend-config=backend.conf

      - name: public infrastructure
        run: |
            echo init terrafom and apply
            cd infra
            terraform apply -auto-approve -var "docker_url_images=${{ steps.build-image-backend.outputs.image-url }}" -var "docker_image_backend=${{ steps.build-image-backend.outputs.image-backend }}" -var "docker_image_syn=${{ steps.build-image-synthesizer.outputs.image-syn }}" -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var "password_ec2=${{ secrets.SSH_KEY }}" -var "repository_name=${{ github.repository }}"